// File generated by Antigravity.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps on platforms.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbR-DnLbUJ7rk7iv3NnkD05fpdoIeaODo',
    appId: '1:74949964677:web:2a38b349c0727c596d0aec',
    messagingSenderId: '74949964677',
    projectId: 'chat-app-20953',
    authDomain: 'chat-app-20953.firebaseapp.com',
    storageBucket: 'chat-app-20953.firebasestorage.app',
    measurementId: 'G-7WYM52ZLPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqypjQm7-5696bHTP7zm6uXqM70rm5x9I',
    appId: '1:74949964677:android:691ad6cc65f1570e6d0aec',
    messagingSenderId: '74949964677',
    projectId: 'chat-app-20953',
    storageBucket: 'chat-app-20953.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBdE3o1nkztmLwIZBMjmmxtHpV5_fUWQ0',
    appId: '1:74949964677:ios:ae643c1a75f8ac9a6d0aec',
    messagingSenderId: '74949964677',
    projectId: 'chat-app-20953',
    storageBucket: 'chat-app-20953.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
